CREATE DATABASE DE05
CREATE TABLE PHONGBAN
(
	MAPB NVARCHAR (50) NOT NULL PRIMARY KEY,
	TENPB NVARCHAR (50) NULL,
	NGANSACH MONEY NULL

)
INSERT INTO PHONGBAN 
VALUES  ('HC','HÀNH CHÍNH',5000000),
		('KT','KỸ THUẬT',7000000),
		('KD','KINH DOANH',10000000)
CREATE TABLE CONGVIEC
(
	MACV NVARCHAR (50) NOT NULL PRIMARY KEY,
	TENCV NVARCHAR (50) NULL,
	LUONG_MIN MONEY NULL,
	LUONG_MAX MONEY NULL
)
INSERT INTO CONGVIEC
VALUES  ('CV01','SỮA CHỮA ĐIỆN NƯỚC',200000,800000),
		('CV02','DỌN DẸP',100000,500000),
		('CV03','BÁN SẢN PHẨM',800000,2200000)
CREATE TABLE NHANVIEN 
(
	MANV NVARCHAR (50) NOT NULL PRIMARY KEY,
	HOTENNV NVARCHAR (50) NULL,
	LCB MONEY NULL,
	NGAYSINH DATETIME NULL,
	GT NVARCHAR (50) NULL,
	MACV NVARCHAR (50) NOT NULL,
	MAPB NVARCHAR (50) NOT NULL,

	CONSTRAINT FK_NV_PB FOREIGN KEY (MAPB) REFERENCES PHONGBAN,
	CONSTRAINT FK_NV_CV FOREIGN KEY (MACV) REFERENCES CONGVIEC
)
INSERT INTO NHANVIEN
VALUES  ('NV01','TRẦN HOÀNG ANH',5000000,'08-08-1977','NAM','CV02','KT'),
		('NV02','NGUYỄN TRÀ MY',4000000,'10-20-1982','NỮ','CV02','HC'),
		('NV03','LÊ TUẤN VŨ',6000000,'10-11-1991','NAM','CV01','KD')
-----------------------------------------------------------------------
--a. Hiển thị các nhân viên mà có tuổi từ 40 trở lên bao gồm các thông tin sau: MANV, HOTEN, TENCV, LUONG, NGAYSINH, TUỔI. (1 điểm)
SELECT A.MANV,A.HOTENNV,B.TENCV,A.LCB,A.NGAYSINH,(YEAR(GETDATE()) - YEAR(NGAYSINH)) AS 'TUỔI' FROM NHANVIEN A,CONGVIEC B
WHERE A.MACV = B.MACV AND (YEAR(GETDATE()) - YEAR(NGAYSINH)) > 40
--b. Hiển thị các nhân viên có LUONG_MIN từ 950000 đến 1300000 bao gồm các thông tin: MANV, HOTENNV, TENCV, TENPB, LUONG_MIN. (1 điểm)
SELECT A.MANV,A.HOTENNV,B.TENCV,C.TENPB,B.LUONG_MIN FROM NHANVIEN A,CONGVIEC B,PHONGBAN C
WHERE A.MAPB = C.MAPB AND B.MACV = A.MACV AND LUONG_MIN BETWEEN 950000 AND 1300000
--c. Hiển thị các thông tin NHANVIEN  họ nguyễn bao gồm các thông tin: MNV, TENNV, TENPB, TENCV. (1 điểm) 
SELECT A.MANV,A.HOTENNV,B.TENCV,C.TENPB FROM NHANVIEN A,CONGVIEC B,PHONGBAN C
WHERE A.MAPB = C.MAPB AND B.MACV = A.MACV AND HOTENNV LIKE 'NGUYỄN%'
--d. Liệt kê các nhân viên có LCB cao nhất gồm các thông tin: MANV, HOTENNV, LCB, TENPB. (1 điểm)
SELECT TOP 1 A.MANV,A.HOTENNV,A.LCB,C.TENPB FROM NHANVIEN A,PHONGBAN C
WHERE A.MAPB = C.MAPB ORDER BY A.LCB DESC
--e. Hiển thị thông tin của những phòng ban không có nhân viên nào gồm: MAPB, TENPB. (1 điểm).
SELECT C.MAPB,C.TENPB FROM PHONGBAN C
WHERE NOT EXISTS (SELECT MAPB FROM NHANVIEN A, PHONGBAN B WHERE A.MAPB = B.MAPB)
--f. Chèn thêm thông tin vào bảng NHANVIEN (Dữ liệu các cột không được để trống) (1 điểm).
INSERT INTO NHANVIEN
VALUES  ('NV02','TRẦN THỊ TRÀ GIANG',7000000,'10-10-1999','NỮ','CV02','HC')

--g.  Xóa toàn bộ thông tin MACV là CV02. (1 điểm).
DELETE CONGVIEC
WHERE MACV = 'CV02'