CREATE DATABASE DE4
CREATE TABLE MATHANG
(
	MAHANG NVARCHAR (50) NOT NULL PRIMARY KEY,
	TENHANG NVARCHAR (50) NULL,
	DONGIA MONEY NULL

)
INSERT INTO MATHANG
VALUES  ('M1','DƯỠNG MÔI OHUI',200000),
		('M2','TINH CHẤT OHUI',1000000),
		('M3','KEM DƯỠNG OHUI',550000)

CREATE TABLE KHACHHANG
(
	MAKH  NVARCHAR (50) NOT NULL PRIMARY KEY,
	TENKH  NVARCHAR (50) NULL,
	GIOITINH  NVARCHAR (50) NULL,
	QUENQUAN  NVARCHAR (50) NULL

)
INSERT INTO KHACHHANG
VALUES  ('K1','TRẦN TRIỆU VY','NỮ','HÀ NỘI'),
		('K2','TRẦN ĐÌNH TRỌNG','NAM','THÁI BÌNH'),
		('K3','MINH HÀ','NỮ','SÀI GÒN')

CREATE TABLE HOADON 
(
	SOPHIEU  NVARCHAR (50) NOT NULL,
	NGAYLAP DATETIME NULL,
	MAKH  NVARCHAR (50) NOT NULL

	CONSTRAINT PK1 PRIMARY KEY (SOPHIEU,MAKH),
	CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
)
INSERT INTO HOADON
VALUES  ('P1','03/03/2019','K1'),
		('P2','08/03/2019','K2'),
		('P3','08/04/2019','K3')

CREATE TABLE CTHOADON
(
	SOPHIEU  NVARCHAR (50) NOT NULL,
	MAHANG  NVARCHAR (50) NOT NULL,
	SOLUONG INT NULL
	
	CONSTRAINT PK2 PRIMARY KEY (SOPHIEU,MAHANG),
	CONSTRAINT FK_CTHOADON_MAHANG FOREIGN KEY (MAHANG) REFERENCES MATHANG(MAHANG)
)
INSERT INTO CTHOADON
VALUES  ('P1','M1',2),
		('P1','M2',3),
		('P2','M2',1)

SELECT * FROM KHACHHANG 
SELECT * FROM HOADON 
SELECT * FROM MATHANG 
SELECT * FROM CTHOADON 

--Câu 2: Đưa ra thông tin: Makh, Tenkh, Gioitinh của những khách hàng có Họ Nguyễn và Quequan là ‘Hà Nội’. (1đ). 
SELECT A.MAKH,A.TENKH,A.GIOITINH FROM KHACHHANG A WHERE TENKH LIKE 'NGUYỄN%' AND A.QUENQUAN = 'HÀ NỘI'
--Câu 3: Đưa ra thông tin danh sách các khách hàng (Makh, Tenkh, tổng tiền) có tổng thành tiền của các hóa đơn từ 1.000.000 trở lên. Trong đó tổng tiền=số lượng*Đơn giá (1đ)
SELECT A.MAKH,A.TENKH,SUM(B.DONGIA * C.SOLUONG) AS 'TONG TIEN' FROM KHACHHANG A,MATHANG B,CTHOADON C,HOADON D 
WHERE A.MAKH = D.MAKH AND B.MAHANG = C.MAHANG AND C.SOPHIEU = D.SOPHIEU GROUP BY A.MAKH,A.TENKH HAVING SUM(B.DONGIA * C.SOLUONG) > 1000000 
--Câu 4: Cho biết thông tin khách hàng chưa đặt đơn hàng nào. Thông tin gồm: Makh, Tenkh (1đ)
SELECT * FROM KHACHHANG 
WHERE NOT EXISTS (SELECT MAKH FROM HOADON WHERE KHACHHANG.MAKH = HOADON.MAKH)
--Câu 5: Liệt kê thông tin: Makh, Tenkh, Mahang, Tenhang, Dongia, Soluong của khách hàng có tên khách hàng là Trần Triệu Vy . (1đ)
SELECT A.MAKH,A.TENKH,B.MAHANG,B.TENHANG,B.DONGIA,C.SOLUONG FROM KHACHHANG A,MATHANG B,CTHOADON C,HOADON D
WHERE A.MAKH = D.MAKH AND B.MAHANG = C.MAHANG AND C.SOPHIEU = D.SOPHIEU AND A.TENKH = 'TRẦN TRIỆU VY'
--Câu 6: Thêm một bản ghi mới vào chitiethoadon,dữ liệu phù hợp( không được nhập giá trị null). (1đ)
INSERT INTO CTHOADON 
VALUES ()
--Câu 7: Thay đổi quê quán của khách hàng Minh Hà thành ‘Miền Tây’ (1đ)
UPDATE KHACHHANG
SET QUENQUAN = 'MIỀN TÂY'
WHERE TENKH = 'MINH HÀ'
--Câu 8: Xóa mặt hàng có tên hàng ‘Kem dưỡng Ohui’ (1đ)
DELETE MATHANG
WHERE TENHANG = 'KEM DƯỠNG OHUI'