CREATE DATABASE DE5ASS
CREATE TABLE PHONGBAN
(
	MAPB NVARCHAR (50) NOT NULL PRIMARY KEY,
	TENPB NVARCHAR (50) NULL,
	NGANSACH MONEY NULL

)
INSERT INTO PHONGBAN
VALUES  ('HC','Hành Chính',5000000),
		('KT','Kỹ Thuật',7000000),
		('KD','Kinh Doanh',10000000)
CREATE TABLE CONGVIEC
(
	MACV NVARCHAR (50) NOT NULL PRIMARY KEY,
	TENCV NVARCHAR (50) NULL,
	LUONG_MIN MONEY NULL,
	LUONG_MAX MONEY NULL

)
INSERT INTO CONGVIEC
VALUES  ('CV01','Sữa chữa điện nước',200000,800000),
		('CV02','Dọn dẹp',100000,500000),
		('CV03','Bán sản phẩm',800000,2200000)
CREATE TABLE NHANVIEN
(
	MANV NVARCHAR (50) NOT NULL ,
	HOTENNV NVARCHAR (50) NULL,
	LCB MONEY NULL,
	NGAYSINH DATETIME NULL,
	GT  NVARCHAR (50) NULL,
	MACV NVARCHAR (50) NOT NULL,
	MAPB NVARCHAR (50) NOT NULL

	CONSTRAINT PK1 PRIMARY KEY (MANV,MACV,MAPB),

	CONSTRAINT FK_1 FOREIGN KEY (MACV) REFERENCES CONGVIEC(MACV)
)
INSERT INTO NHANVIEN
VALUES  ('NV1','Trần Hoàng Anh',5000000,'08-08-1977','Nam','CV02','KT'),
		('NV2','Nguyễn Trà My',4000000,'10-20-1982','Nữ','CV02','HC'),
		('NV3','Lê Tuấn Vũ',6000000,'10-11-1991','Nam','CV01','KD')
--A--
SELECT MANV,HOTENNV,TENCV,LCB,NGAYSINH,YEAR(GETDATE()) - YEAR(NGAYSINH) AS 'TUOI' FROM NHANVIEN,CONGVIEC 
WHERE NHANVIEN.MACV = CONGVIEC.MACV AND (YEAR(GETDATE()) - YEAR(NGAYSINH)) > 40
--B--
SELECT C.MANV,C.HOTENNV,B.TENCV,A.TENPB,B.LUONG_MIN FROM PHONGBAN A,CONGVIEC B,NHANVIEN C
WHERE A.MAPB = C.MAPB AND B.MACV = C.MACV and (LUONG_MIN BETWEEN 950000 AND 1300000)
--C--
SELECT MANV, HOTENNV, TENPB, TENCV
FROM NHANVIEN A INNER JOIN PHONGBAN B ON A.MAPB = B.MAPB
INNER JOIN CONGVIEC C ON A.MACV = C.MACV
WHERE HOTENNV LIKE ('Nguyễn%')
--D--
SELECT TOP 1 C.MANV,C.HOTENNV,C.LCB,A.TENPB FROM PHONGBAN A, NHANVIEN C
ORDER BY LCB DESC
--E--
SELECT B.TENPB,B.MAPB FROM PHONGBAN B
WHERE  B.MAPB NOT IN (SELECT C.MACV FROM NHANVIEN C,PHONGBAN B WHERE B.MAPB = C.MAPB )
--F--
--INSERT INTO NHANVIEN
--VALUES ('','',,'','','','')
--G--
DELETE FROM NHANVIEN A  
WHERE A.MACV = 'CV02'
SELECT * FROM NHANVIEN