CREATE DATABASE QLDUAN

CREATE TABLE NHANVIEN
(
	MANV NVARCHAR (50) NOT NULL PRIMARY KEY,
	HOTEN NVARCHAR (50) NULL,
	NGAYSINH DATETIME NULL,
	GT NVARCHAR (50) NULL,
	MA_P NVARCHAR (50) NULL,
	LUONG MONEY  NULL
) 
ALTER TABLE NHANVIEN
	ADD CONSTRAINT FK_1 FOREIGN KEY (MA_P) REFERENCES PHONG(MA_P)
CREATE TABLE PHONG
(
	MA_P NVARCHAR (50) NOT NULL PRIMARY KEY,
	TENPHONG NVARCHAR (50) NULL
)
CREATE TABLE DIA_DIEM_DV
(
	MA_DV NVARCHAR (50) NOT NULL PRIMARY KEY,
	DIA_DIEM  NVARCHAR (50) NULL
)
CREATE TABLE DU_AN
(
	MA_DA NVARCHAR (50) NOT NULL PRIMARY KEY,
	TEN_DA NVARCHAR (50) NULL,
	DIADIEM_DA NVARCHAR (50) NULL,
	MA_DV NVARCHAR (50) NULL,
)
ALTER TABLE DU_AN
	ADD CONSTRAINT FK_2 FOREIGN KEY (MA_DV) REFERENCES DIA_DIEM_DV(MA_DV)
CREATE TABLE CHAMCONG 
(
	MANV NVARCHAR (50) NULL,
	MA_DA NVARCHAR (50) NULL,
	SO_GIO INT NOT NULL PRIMARY KEY
)
--ALTER TABLE CHAMCONG
--	ADD CONSTRAINT FK_34 FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
ALTER TABLE CHAMCONG
	ADD CONSTRAINT FK_45 FOREIGN KEY (MA_DA) REFERENCES DU_AN(MA_DA)
-------------------------------------------
--A
--SELECT * INTO CHAMCONG_TEST FROM CHAMCONG
SELECT * FROM NHANVIEN_TEST
SELECT * FROM CHAMCONG_TEST
DELETE FROM NHANVIEN_TEST WHERE HOTEN LIKE '% Tèo%'
--B
UPDATE NHANVIEN_TEST
SET LUONG = LUONG + LUONG * 0.05
--C
UPDATE NHANVIEN_TEST
SET LUONG = LUONG + LUONG * 0.05
WHERE MA_P = 'P2'
--D--
DELETE FROM NHANVIEN_TEST WHERE MANV like '05' or MANV like '06' or MANV like '03'
--E
DELETE FROM CHAMCONG_TEST
WHERE EXISTS (SELECT * FROM NHANVIEN_TEST WHERE  CHAMCONG_TEST.MANV = NHANVIEN_TEST.MANV AND NHANVIEN_TEST.MA_P LIKE 'P1')
--F
UPDATE NHANVIEN_TEST
SET LUONG = LUONG + LUONG * 0.1
WHERE EXISTS (SELECT TOP 1 MAX(SO_GIO) FROM CHAMCONG_TEST WHERE CHAMCONG_TEST.MANV = NHANVIEN_TEST.MANV ORDER BY SO_GIO DESC)