create database QLKINHDOANH

create table KHACHHANG
(
	MAKHACHHANG NVARCHAR (50) NOT NULL PRIMARY KEY,
	TENCONGTY NVARCHAR (50) NULL,
	TENGIAODICH NVARCHAR (50) NULL,
	DIACHI NVARCHAR (50) NULL,
	EMAIL NVARCHAR (50) NULL,
	DIENTHOAI NVARCHAR (10) NULL,
	FAX NVARCHAR (50) NULL,

)
SELECT * FROM KHACHHANG
CREATE TABLE DONGIAOHANG
(
	SOHOADON NVARCHAR (50) NOT NULL PRIMARY KEY,
	MAKHACHHANG NVARCHAR (50) NULL,
	MANHANVIEN NVARCHAR (50) NULL,
	NGAYDATHANG DATETIME NULL,
	NGAYGIAOHANG DATETIME NULL,
	NGAYCHUYENHANG DATETIME NULL,
	NOIGIAODICH NVARCHAR (50) NULL,
)
CREATE TABLE NHAVIEN
(
	MANHANVIEN NVARCHAR (50) NOT NULL PRIMARY KEY,
	HO NVARCHAR (50) NULL,
	TEN NVARCHAR (50) NULL,
	NGAYSINH DATETIME NULL,
	NGAYLAMVIEC DATETIME NULL,
	DIACHI NVARCHAR (50) NULL,
	DIENTHOAI NVARCHAR (50) NULL,
	LUONGCOBAN MONEY NULL,
	PHUCAP MONEY NULL,

)
CREATE TABLE NHACUNGCAP 
(
	MACONGTY NVARCHAR (50) NOT NULL PRIMARY KEY,
	TENCONGTY NVARCHAR (50) NULL,
	TENGIAODICH NVARCHAR (50) NULL,
	DIACHI NVARCHAR (50) NULL,
	DIENTHOAI NVARCHAR (50) NULL,
	FAX NVARCHAR (50) NULL,
	EMAIL NVARCHAR (50) NULL,

)
CREATE TABLE CHITIETDATHANG
(
	SOHOADON NVARCHAR (50) NOT NULL PRIMARY KEY,
	MAHANG NVARCHAR (50) NOT NULL,
	GIABAN NVARCHAR (50) NULL,
	SOLUONG INT NULL,
	MUCGIAMGIA NVARCHAR (50) NULL,
)
CREATE TABLE MAHANG
(
	MAHANG NVARCHAR (50) NOT NULL PRIMARY KEY,
	TENHANG NVARCHAR (50) NULL,
	MACONGTY NVARCHAR (50) NULL,
	MALOAIHANG NVARCHAR (50) NULL,
	SOLUONG INT NULL,
	DONVITINH NVARCHAR (50) NULL,
	GIAHANG MONEY NULL,
)
CREATE TABLE LOAIHANG
(
	MALOAIHANG NVARCHAR (50) NOT NULL PRIMARY KEY,
	TENLOAIHANG NVARCHAR (50) NULL,
)

ALTER TABLE KHACHHANG
	DROP COLUMN TENCONGTY
ALTER TABLE KHACHHANG
	ADD TENKHACHHANG NVARCHAR (50) NULL;
SELECT * FROM KHACHHANG
SELECT TOP 3 MAKHACHHANG,TENKHACHHANG,DIACHI,DIENTHOAI FROM KHACHHANG
Select * from KHACHHANG where DIACHI like 'HANOI'
SELECT MAKHACHHANG,TENKHACHHANG,DIACHI FROM KHACHHANG
SELECT MAHANG,TENHANG,AVG(SOLUONG*GIAHANG) FROM MAHANG GROUP BY MAHANG,TENHANG
SELECT MAHANG,TENHANG,SOLUONG FROM MAHANG  WHERE  SOLUONG BETWEEN 70 AND 90 order by SOLUONG DESC
SELECT SOHOADON,SOLUONG,GIABAN FROM CHITIETDATHANG WHERE (GIABAN > 1000000)
SELECT * FROM NHACUNGCAP WHERE DIACHI LIKE 'HATINH'
SELECT LUONGCOBAN +''+PHUCAP AS "LUONG" FROM NHANVIEN
SELECT * FROM NHANVIEN WHERE (LUONGCOBAN + PHUCAP > 10000000)


--2. 1 Cho biết danh sách các dối tác cung cấp hàng cho công ty.
SELECT * FROM NHACUNGCAP
--2. 2 Mã hàng, tên hàng và số luợng của các mặt hàng hiện có trong công ty.
SELECT MAHANG,TENHANG,SOLUONG FROM MAHANG 
--2. 3 Họ tên và dịa chỉ và nam bắt dầu làm việc của các nhân viên trong công ty.
SELECT HO+' '+TEN AS 'HO TEN',A.DIACHI,A.NGAYLAMVIEC FROM NHANVIEN A
--2. 4 Ðịa chỉ và diện thoại của nhà cung cấp có tên giao dịch VINAMILK là gì?
SELECT B.DIACHI,B.DIENTHOAI FROM NHACUNGCAP B WHERE B.TENGIAODICH LIKE ('VINAMILK')
--2. 5 Cho biết mã và tên của các mặt hàng có giá lớn hon 100000 và số luợng hiện có ít hon 50.
SELECT C.MAHANG,C.TENHANG FROM MAHANG C WHERE (GIAHANG > 100000) AND (C.SOLUONG <50) 
--2. 6 Cho biết mỗi mặt hàng trong công ty do ai cung cấp.
SELECT C.TENHANG,D.TENCONGTY FROM MAHANG C,NHACUNGCAP D WHERE (C.MACONGTY = D.MACONGTY)
--2. 7 Công ty Việt Tiến dã cung cấp những mặt hàng nào?
SELECT C.TENHANG,D.TENCONGTY FROM MAHANG C,NHACUNGCAP D WHERE (C.MACONGTY = D.MACONGTY) AND (TENCONGTY LIKE 'VIETTIEN')
--2. 8 Loại hàng thực phẩm do những công ty nào cung cấp và dịa chỉ của các công ty dó là gì?
SELECT B.MALOAIHANG,B.TENLOAIHANG,D.TENCONGTY,D.DIACHI FROM LOAIHANG B, MAHANG C,NHACUNGCAP D WHERE (C.MACONGTY = D.MACONGTY) AND (B.MALOAIHANG = C.MALOAIHANG)
--2. 9 Những khách hàng nào (tên giao dịch) dã dặt mua mặt hàng Sữa hộp XYZ của công ty?
 SELECT A.TENKHACHHANG,B.TENCONGTY FROM KHACHHANG A,NHACUNGCAP B WHERE (A.TENGIAODICH LIKE 'SUAHOPXYZ' AND B.TENGIAODICH LIKE 'SUAHOPXYZ')
--2. 10 Ðon dặt hàng số 1 do ai dặt và do nhân viên nào lập, thời gian và dịa diểm giao hàng là ở dâu?
SELECT TOP 1 A.TENKHACHHANG,B.HO+' '+B.TEN AS 'HO TEN',C.NGAYCHUYENHANG,C.NOIGIAODICH FROM KHACHHANG A,NHANVIEN B,DONDATHANG C
--2. 11 Hãy cho biết số tiền luong mà công ty phải trả cho mỗi nhân viên là bao nhiêu (luong = luong co bản + phụ cấp).
SELECT HO+' '+TEN AS 'HO TEN',SUM(LUONGCOBAN + PHUCAP) AS 'LUONG' FROM NHANVIEN GROUP BY HO+' '+TEN
--2. 12 Trong don dặt hàng số 3 dặt mua những mặt hàng nào và số tiền mà khách hàng
--phải trả cho mỗi mặt hàng là bao nhiêu (số tiền phải trả duợc tính theo công thức SOLUONG×GIABAN – SOLUONG×GIABAN×MUCGIAMGIA/100)
SELECT  B.SOHOADON,A.TENHANG,SUM(B.SOLUONG*B.GIABAN - (B.SOLUONG*B.GIABAN*B.MUCGIAMGIA/100)) AS 'TIEN TRA' FROM MAHANG A ,CHITIETDATHANG B WHERE (A.MAHANG = B.MAHANG) AND (B.SOHOADON LIKE '3') GROUP BY B.SOHOADON,A.TENHANG
--2. 13 Hãy cho biết có những khách hàng nào lại chính là dối tác cung cấp hàng của công ty (tức là có cùng tên giao dịch).
SELECT A.TENKHACHHANG,B.TENCONGTY FROM KHACHHANG A,NHACUNGCAP B WHERE (A.TENGIAODICH = B.TENGIAODICH)
--2. 14 Trong công ty có những nhân viên nào có cùng ngày sinh

--SELECT V1.MANHANVIEN,V1.HO,V1.TEN ,V2.MANHANVIEN,V2.HO,V2.TEN  
--FROM dbo.NHANVIEN V1  INNER JOIN dbo.NHANVIEN V2 
--ON V2.NGAYSINH=V1.NGAYSINH
--WHERE V2.MANHANVIEN !=V1.MANHANVIEN
SELECT A.MANHANVIEN, A.HO+' '+A.TEN AS 'HO TEN',A.NGAYSINH FROM NHANVIEN A,NHANVIEN B  WHERE (B.MANHANVIEN != A.MANHANVIEN) AND (A.NGAYSINH = B.NGAYSINH)
--2. 15 Những don dặt hàng nào yêu cầu giao hàng ngay tại công ty dặt hàng và những don dó là của công ty nào?
SELECT A.TENGIAODICH,B.TENCONGTY,A.TENKHACHHANG,C.NOIGIAODICH FROM KHACHHANG A,NHACUNGCAP B,DONDATHANG C WHERE (A.MAKHACHHANG = C.MAKHACHHANG) AND (A.TENGIAODICH = B.TENGIAODICH)  AND (C.NOIGIAODICH = 'TAICONGTY')
----Tích
--SELECT   B.TEN_DUAN, A.HO_NV, A.TEN_NV, C.NGAY_THAM_GIA, C.NGAY_KET_THUC
--FROM NHAN_VIEN  A  , DU_AN  B, QUANLY_DUAN  C 
--WHERE  (B.MA_DUAN = C.MA_DUAN )
--AND  (A.ID_NhanVien = C.MA_NHANVIEN);
----Inner join
--SELECT  ID_NhanVien, HO_NV, TEN_NV, TEN_PB   
--FROM  PHONG_BAN  A INNER JOIN NHAN_VIEN B 
--ON A.MA_PB = B.PHG
----Left outer
--SELECT A.ID_NhanVien, A.HO_NV, A.TEN_NV, B.TEN_PB
--FROM PHONG_BAN B left JOIN NHAN_VIEN A 
--ON B.MA_PB = A.PHG 
--WHERE B.MA_PB='CNTT';
--SELECT *  FROM NHAN_VIEN 
--WHERE LUONG > (SELECT AVG(LUONG) FROM NHAN_VIEN)
----Mệnh đề In
--SELECT  *  FROM NHAN_VIEN 
--WHERE PHG IN  (SELECT  MA_PB FROM PHONG_BAN WHERE TEN_PB LIKE 'phòng %')
